version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 829108230080.dkr.ecr.us-west-2.amazonaws.com

  build:
    commands:
      - echo Building mad-api image...
      - docker build -t guardrails/mad-api:latest -f multi_agent_debate/full_FinalMAD_with_judge/Dockerfile .
      - docker tag guardrails/mad-api:latest 829108230080.dkr.ecr.us-west-2.amazonaws.com/guardrails/mad-api:latest

  post_build:
    commands:
      - echo Pushing mad-api image...
      - docker push 829108230080.dkr.ecr.us-west-2.amazonaws.com/guardrails/mad-api:latest
      - echo Done.
